# services:
#   app1:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: backend-app1
#     environment:
#       INSTANCE_ID: 1
#       ASPNETCORE_URLS: http://+:8080
#     # ports:
#     #   - "4500:8080"

#   app2:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: backend-app2
#     environment:
#       INSTANCE_ID: 2
#       ASPNETCORE_URLS: http://+:8081
#     # ports:
#     #   - "4501:8080"

#   app3:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: backend-app3
#     environment:
#       INSTANCE_ID: 3
#       ASPNETCORE_URLS: http://+:8082
#     # ports:
#     #   - "4502:8080"

#   nginx:
#     image: nginx:latest
#     container_name: nginx-lb
#     ports:
#       - "8000:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro