events {}

http{

    upstream backend{
        #  ip_hash;
        
        server backend-app1:8080;
        server backend-app2:8081;
        server backend-app3:8082;
        # server backend-app3:8082 backup;
        # server backend-app3:8082 down;
    }
    server{
        listen 80;

        location /{
            proxy_pass http://backend;
        }

    }
}